export const shopDataActionTypes = {
  // ADD_DATA_FROM_FIRESTORE: "ADD_DATA_FROM_FIRESTORE",
  GET_COLLECTIONS_START: "GET_COLLECTIONS_START",
  GET_COLLECTIONS_SUCCESS: "GET_COLLECTIONS_SUCCESS",
  GET_COLLECTIONS_ERROR: "GET_COLLECTIONS_ERROR"
}